<a href="https://colab.research.google.com/github/laura-hernando/pml/blob/master/course/Problem003_XxYyNn/003.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Load Boston Housing Dataset
https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_boston.html#sklearn.datasets.load_boston

In [5]:
import numpy as np

In [7]:
from sklearn.datasets import load_boston
house_data = load_boston()

In [8]:
dir(house_data)

['DESCR', 'data', 'feature_names', 'filename', 'target']

In [9]:
house_data['feature_names']

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [10]:
# How many houses are there (N)
N = len(house_data['data'])
print(N)

506


In [11]:
# A house has how many attributes(or features or signals or dimensions or columns)
n = len(house_data['feature_names'])
print(n)
# All attributes together make up a row (or input or x)

13


In [12]:
# Whats the Median value of the first house (target or label or output y)
house_data['target'][0]

24.0

In [13]:
# Whats the value of feature RM (average number of rooms per dwelling) for the last house
index_RM = np.where(house_data['feature_names'] == 'RM')
house_data['data'][-1][index_RM]

array([6.03])

#### House 8 all features
$
\begin{align}
X^{8} 
\end{align}
$


In [14]:
house_data['data'][8]

array([2.1124e-01, 1.2500e+01, 7.8700e+00, 0.0000e+00, 5.2400e-01,
       5.6310e+00, 1.0000e+02, 6.0821e+00, 5.0000e+00, 3.1100e+02,
       1.5200e+01, 3.8663e+02, 2.9930e+01])

#### House 8,  feature 2
(INDUS proportion of non-retail business acres per town)

$
\begin{align}
X_{2}^{8}
\end{align}
$


In [15]:
house_data['data'][8][2]

7.87

#### All houses feature 4
(NOX nitric oxides concentration)

$
\begin{align}
X_{4}
\end{align}
$


In [16]:
house_data['data'][:, 4]

array([0.538 , 0.469 , 0.469 , 0.458 , 0.458 , 0.458 , 0.524 , 0.524 ,
       0.524 , 0.524 , 0.524 , 0.524 , 0.524 , 0.538 , 0.538 , 0.538 ,
       0.538 , 0.538 , 0.538 , 0.538 , 0.538 , 0.538 , 0.538 , 0.538 ,
       0.538 , 0.538 , 0.538 , 0.538 , 0.538 , 0.538 , 0.538 , 0.538 ,
       0.538 , 0.538 , 0.538 , 0.499 , 0.499 , 0.499 , 0.499 , 0.428 ,
       0.428 , 0.448 , 0.448 , 0.448 , 0.448 , 0.448 , 0.448 , 0.448 ,
       0.448 , 0.448 , 0.439 , 0.439 , 0.439 , 0.439 , 0.41  , 0.403 ,
       0.41  , 0.411 , 0.453 , 0.453 , 0.453 , 0.453 , 0.453 , 0.453 ,
       0.4161, 0.398 , 0.398 , 0.409 , 0.409 , 0.409 , 0.413 , 0.413 ,
       0.413 , 0.413 , 0.437 , 0.437 , 0.437 , 0.437 , 0.437 , 0.437 ,
       0.426 , 0.426 , 0.426 , 0.426 , 0.449 , 0.449 , 0.449 , 0.449 ,
       0.489 , 0.489 , 0.489 , 0.489 , 0.464 , 0.464 , 0.464 , 0.445 ,
       0.445 , 0.445 , 0.445 , 0.445 , 0.52  , 0.52  , 0.52  , 0.52  ,
       0.52  , 0.52  , 0.52  , 0.52  , 0.52  , 0.52  , 0.52  , 0.547 ,
      

#### Target value for house 4
$
Y^{4}
$


In [17]:
house_data['target'][4]

36.2

Small *x* and *y* are used to represent a *feature* and *target* of a single house
#### Which among the following could be valid representation?
$
x^{4}\:, \: x_{2}\:,\:y^{4}\:,\:y_{2}
$



In [18]:
# 𝑥2 is the only vaid representation(house with two features). y is scalar because it's of a single house.